theme: pages-themes/minimal@v0.2.0
title: runbk's homepage
description: My personal Github Page.
author: runbk
email: alexdo@outlook.com
description: Example description, blah blah blah...
twitter_username: n/a
github_username: n/a
plugins:
- jekyll-remote-theme
